import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/authProvider";
import { Navbar } from "@/components/nav";
import "./globals.css";
import { ThemeProvider } from "@/context/themeProvider";
import { Sidenav } from "@/components/sidenav/sidenav";
import { SidenavMobile } from "@/components/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            <Sidenav />
            <SidenavMobile>
              <Sidenav isMobileView />
            </SidenavMobile>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
